# Generated by Django 6.1 on 2026-08-22 23:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Новая цена')),
                ('old_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена со скидкой')),
                ('new_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Новая цена со скидкой')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'История цен',
                'db_table': 'pricing_price_history',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Цена со скидкой. None = без скидки.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена со скидкой')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли'), ('USD', 'Доллары'), ('EUR', 'Евро')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='catalog.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'db_table': 'pricing_price',
                'ordering': ('-created_at',),
            },
        ),
    ]
