# Generated by Django 6.0.6 on 2026-06-12 16:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.productvariant', verbose_name='Вариант товара'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['variant'], name='pricing_price_variant_idx'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', Decimal('0.01'))), name='price_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__isnull', True), ('sale_price__lte', models.F('price')), _connector='OR'), name='sale_price_lte_price'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['variant', '-created_at'], name='pricing_hst_var_cr_idx'),
        ),
    ]
