# Generated by Django 6.0.6 on 2026-06-12 16:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order_number', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Номер платежа')),
                ('_payment_number_seq', models.PositiveBigIntegerField(db_index=True, default=0, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('succeeded', 'Успешно оплачен'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменён'), ('refunded', 'Возврат средств')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('method', models.CharField(choices=[('card', 'Банковская карта'), ('sbp', 'СБП'), ('yoomoney', 'ЮMoney'), ('sberpay', 'SberPay'), ('cash', 'При получении')], db_index=True, max_length=20, verbose_name='Метод оплаты')),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Сумма платежа')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма возврата')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Внешний ID')),
                ('provider', models.CharField(db_index=True, max_length=50, verbose_name='Платёжный провайдер')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата оплаты')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('note', models.TextField(blank=True, default='', max_length=1000, verbose_name='Комментарий')),
                ('refund_reason', models.TextField(blank=True, default='', max_length=500, verbose_name='Причина возврата')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Плательщик')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event_type', models.CharField(choices=[('created', 'Платёж создан'), ('status_changed', 'Статус изменён'), ('webhook_received', 'Вебхук получен'), ('refund_initiated', 'Возврат инициирован'), ('refund_completed', 'Возврат завершён'), ('cancelled', 'Платёж отменён'), ('confirmed', 'Платёж подтверждён'), ('callback_received', 'Callback получен'), ('error', 'Ошибка')], db_index=True, max_length=30, verbose_name='Тип события')),
                ('old_status', models.CharField(blank=True, default='', max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(blank=True, default='', max_length=20, verbose_name='Новый статус')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
                ('external_event_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Внешний ID события')),
                ('note', models.TextField(blank=True, default='', max_length=1000, verbose_name='Комментарий')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payment', verbose_name='Платёж')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Событие платежа',
                'verbose_name_plural': 'События платежей',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0'))), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', Decimal('0'))), name='payment_refund_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__lte', models.F('amount'))), name='payment_refund_lte_amount'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['payment', 'event_type'], name='pay_event_payment_type_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['event_type'], name='pay_event_type_idx'),
        ),
    ]
