# Generated by Django 6.1 on 2026-08-22 23:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('event_type', models.CharField(choices=[('created', 'Платёж создан'), ('status_changed', 'Статус изменён'), ('webhook_received', 'Вебхук получен'), ('refund_initiated', 'Возврат инициирован'), ('refund_completed', 'Возврат завершён'), ('cancelled', 'Платёж отменён'), ('confirmed', 'Платёж подтверждён'), ('callback_received', 'Callback получен'), ('error', 'Ошибка')], db_index=True, max_length=30, verbose_name='Тип события')),
                ('old_status', models.CharField(blank=True, default='', max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(blank=True, default='', max_length=20, verbose_name='Новый статус')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные события')),
                ('external_event_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Внешний ID события')),
                ('note', models.TextField(blank=True, default='', max_length=1000, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Событие платежа',
                'verbose_name_plural': 'События платежей',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order_number', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Номер платежа')),
                ('_payment_number_seq', models.PositiveBigIntegerField(db_index=True, default=0, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('succeeded', 'Успешно оплачен'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменён'), ('refunded', 'Возврат средств')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('method', models.CharField(choices=[('card', 'Банковская карта'), ('sbp', 'СБП'), ('yoomoney', 'ЮMoney'), ('sberpay', 'SberPay'), ('cash', 'При получении')], db_index=True, max_length=20, verbose_name='Метод оплаты')),
                ('amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Сумма платежа')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма возврата')),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Внешний ID')),
                ('provider', models.CharField(db_index=True, max_length=50, verbose_name='Платёжный провайдер')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата оплаты')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('note', models.TextField(blank=True, default='', max_length=1000, verbose_name='Комментарий')),
                ('refund_reason', models.TextField(blank=True, default='', max_length=500, verbose_name='Причина возврата')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
    ]
