# Generated by Django 6.1 on 2026-08-22 23:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название кампании')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='Дата начала')),
                ('ended_at', models.DateTimeField(db_index=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('code', models.CharField(db_index=True, help_text='Уникальный код: SUMMER2025, BLACKFRI50 и т.д.', max_length=50, unique=True, verbose_name='Код купона')),
                ('description', models.TextField(blank=True, default='', max_length=1000, verbose_name='Описание')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент от суммы'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=10, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Процент (1-100) или фиксированная сумма в рублях.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Значение скидки')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Только для процентной скидки. Ограничивает сверху.', max_digits=12, null=True, verbose_name='Макс. скидка (₽)')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Заказ должен быть ≥ этой суммы для применения купона.', max_digits=12, verbose_name='Мин. сумма заказа')),
                ('max_total_uses', models.PositiveIntegerField(default=100000, help_text='0 = не ограничено.', verbose_name='Макс. использований (всего)')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Сколько раз один пользователь может применить купон.', verbose_name='Макс. использований (на пользователя)')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Использован (раз)')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='Действует с')),
                ('ended_at', models.DateTimeField(db_index=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='discounts.campaign', verbose_name='Кампания')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['code', 'is_active'], name='coupon_code_active_idx')],
            },
        ),
    ]
