# Generated by Django 6.1 on 2026-08-29 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0002_couponusage"),
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="couponusage",
            name="uq_coupon_usage_coupon_order",
        ),
        migrations.AddConstraint(
            model_name="couponusage",
            constraint=models.UniqueConstraint(
                fields=("order",), name="uq_coupon_usage_order"
            ),
        ),
    ]
