# Generated by Django 6.1 on 2026-08-22 23:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('in', 'Поступление'), ('out', 'Списание (отгрузка)'), ('reserve', 'Резервирование'), ('release', 'Освобождение резерва'), ('adjustment', 'Корректировка')], db_index=True, max_length=20, verbose_name='Тип движения')),
                ('delta', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Величина изменения')),
                ('quantity_before', models.PositiveIntegerField(verbose_name='Остаток до')),
                ('quantity_after', models.PositiveIntegerField(verbose_name='Остаток после')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Движение склада',
                'verbose_name_plural': 'Движения склада',
                'db_table': 'inventory_stockmovement',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('quantity', models.PositiveIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество на складе')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Зарезервировано')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Если количество на складе ≤ этого значения — отправляется уведомление о необходимости пополнения.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Порог мало товара')),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Остаток на складе',
                'verbose_name_plural': 'Остатки на складе',
                'db_table': 'inventory_stock',
                'ordering': ('-created_at',),
            },
        ),
    ]
