# Generated by Django 6.1 on 2026-08-22 23:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(help_text='Например: «Курьерская доставка (Москва)»', max_length=200, verbose_name='Название')),
                ('shipping_type', models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз'), ('post', 'Почта'), ('express', 'Экспресс')], db_index=True, default='courier', max_length=20, verbose_name='Тип доставки')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Фиксированная часть стоимости доставки.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Базовая стоимость (₽)')),
                ('price_per_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Добавочная стоимость за каждый кг веса.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Стоимость за 1 кг (₽)')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Если сумма заказа ≥ этого значения — доставка бесплатная. Пусто = всегда платная.', max_digits=12, null=True, verbose_name='Бесплатная доставка от (₽)')),
                ('max_shipping_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Верхний предел стоимости доставки. Пусто = без ограничений.', max_digits=10, null=True, verbose_name='Макс. стоимость доставки (₽)')),
                ('estimated_days_min', models.PositiveSmallIntegerField(default=1, help_text='Минимальное количество дней для доставки.', verbose_name='Мин. срок доставки (дни)')),
                ('estimated_days_max', models.PositiveSmallIntegerField(default=7, help_text='Максимальное количество дней для доставки.', verbose_name='Макс. срок доставки (дни)')),
                ('max_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('30.000'), help_text='Максимальный вес одной посылки (кг).', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Макс. вес (кг)')),
                ('pickup_address', models.TextField(blank=True, default='', help_text='Заполняется только для самовывоза.', max_length=500, verbose_name='Адрес пункта выдачи')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='Меньшее значение = показывается выше.', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
                'ordering': ('sort_order', 'base_price'),
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название зоны')),
                ('zone_code', models.CharField(db_index=True, help_text='Уникальный код зоны: msk, central, fareast. Используется для программного определения зоны по адресу.', max_length=50, unique=True, verbose_name='Код зоны')),
                ('regions', models.JSONField(blank=True, default=list, help_text='Список регионов/городов, входящих в зону. Формат: ["Москва", "Московская область"]. Используется для определения зоны по адресу доставки.', verbose_name='Регионы')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Зона доставки',
                'verbose_name_plural': 'Зоны доставки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('preparing', 'Собирается'), ('in_transit', 'В пути'), ('out_for_delivery', 'У курьера'), ('delivered', 'Доставлено'), ('failed', 'Не доставлено'), ('returned', 'Возврат')], db_index=True, default='preparing', max_length=25, verbose_name='Статус')),
                ('tracking_number', models.CharField(blank=True, db_index=True, default='', help_text='Трек-номер от службы доставки.', max_length=50, verbose_name='Трек-номер')),
                ('internal_tracking', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Внутренний трек')),
                ('_tracking_seq', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Стоимость доставки (₽)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Фактический вес отправления в кг.', max_digits=8, null=True, verbose_name='Вес (кг)')),
                ('notes', models.TextField(blank=True, default='', help_text='Заметки о доставке (для склада / службы доставки).', verbose_name='Примечания')),
                ('shipped_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата отправки')),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата доставки')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Отправление',
                'verbose_name_plural': 'Отправления',
                'ordering': ('-created_at',),
            },
        ),
    ]
