# Generated by Django 6.0.6 on 2026-06-12 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Ключ сессии')),
                ('source', models.CharField(choices=[('organic', 'Органический'), ('search', 'Поисковик'), ('social', 'Соцсети'), ('referral', 'Реферал'), ('direct', 'Прямой')], db_index=True, default='direct', max_length=20, verbose_name='Источник')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalog.product', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр товара',
                'verbose_name_plural': 'Просмотры товаров',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['product', 'created_at'], name='prodview_prod_created_idx'), models.Index(fields=['source', 'created_at'], name='prodview_src_created_idx'), models.Index(fields=['session_key', 'product'], name='prodview_sess_prod_idx')],
            },
        ),
    ]
