# Generated by Django 6.1 on 2026-08-22 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Ключ сессии')),
                ('source', models.CharField(choices=[('organic', 'Органический'), ('search', 'Поисковик'), ('social', 'Соцсети'), ('referral', 'Реферал'), ('direct', 'Прямой')], db_index=True, default='direct', max_length=20, verbose_name='Источник')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Просмотр товара',
                'verbose_name_plural': 'Просмотры товаров',
                'ordering': ('-created_at',),
            },
        ),
    ]
