# Generated by Django 6.1 on 2026-08-22 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', 'created_at'], name='prodview_prod_created_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['source', 'created_at'], name='prodview_src_created_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['session_key', 'product'], name='prodview_sess_prod_idx'),
        ),
    ]
