# Generated by Django 6.1 on 2026-08-22 23:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, help_text='Для админки — поясняет, что означает этот атрибут.', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/%Y/%m/', verbose_name='Логотип')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('url_path', models.CharField(blank=True, db_index=True, editable=False, max_length=1000, verbose_name='URL-путь')),
                ('full_name_cached', models.CharField(blank=True, editable=False, max_length=2000, verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('color_hex', models.CharField(blank=True, help_text='Для цветных атрибутов: #FF0000, #0000FF и т.д.', max_length=7, verbose_name='HEX-цвет')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.attribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
                'ordering': ('attribute__name', 'value'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public UUID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='SEO slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('search_vector', models.TextField(blank=True, default='', editable=False, null=True, verbose_name='Поисковый текст (SQLite fallback)')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('manufacturer_code', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Артикул производителя')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('out_of_stock', 'Нет в наличии'), ('archived', 'Архив')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Показывать в блоке «Рекомендуем» на главной.', verbose_name='Рекомендуемый')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Запланированная дата публикации. null = не опубликован. Заполняется при переходе в ACTIVE.', null=True, verbose_name='Дата публикации')),
                ('min_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Автоматически пересчитывается при изменении цен вариантов. null = у товара нет вариантов с ценой.', max_digits=12, null=True, verbose_name='Минимальная цена')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Автоматически пересчитывается при изменении цен вариантов. null = у товара нет вариантов с ценой.', max_digits=12, null=True, verbose_name='Максимальная цена')),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))], verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('views_count', models.PositiveBigIntegerField(default=0, verbose_name='Просмотры')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Бренд')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.category', verbose_name='Категории')),
                ('primary_category', models.ForeignKey(help_text='Используется для breadcrumbs и canonical URL.', on_delete=django.db.models.deletion.PROTECT, related_name='primary_products', to='catalog.category', verbose_name='Основная категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, help_text='Описание изображения для SEO и доступности. Пустое поле = будет использовано название товара.', max_length=255, verbose_name='Alt-текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(blank=True, help_text='Отображается в listing-е и карточке товара.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_products', to='catalog.productimage', verbose_name='Главное изображение'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул (SKU)')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Штрихкод')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длина')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Высота')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True, unique=True, verbose_name='Слаг')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товара',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='catalog.attribute', verbose_name='Атрибут')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='catalog.attributevalue', verbose_name='Значение')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Атрибут варианта',
                'verbose_name_plural': 'Атрибуты вариантов',
                'ordering': ('attribute__name',),
            },
        ),
        migrations.AddConstraint(
            model_name='attributevalue',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='unique_attribute_value'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_main'], name='productimage_product_main_idx'),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('product',), name='unique_main_product_image'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='variant_product_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'primary_category'], name='product_status_category_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'brand'], name='product_status_brand_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-rating'], name='product_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['min_price'], name='product_min_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-max_price'], name='product_max_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='product_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at', 'is_featured'], name='product_featured_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 5)), name='product_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('reviews_count__gte', 0)), name='product_reviews_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('views_count__gte', 0)), name='product_views_count_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('min_price__isnull', True), ('min_price__gte', 0), _connector='OR'), name='product_min_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('min_price__isnull', True), ('max_price__isnull', True), ('max_price__gte', models.F('min_price')), _connector='OR'), name='product_max_price_gte_min'),
        ),
        migrations.AddIndex(
            model_name='variantattribute',
            index=models.Index(fields=['attribute', 'value'], name='variantattr_attr_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='variantattribute',
            constraint=models.UniqueConstraint(fields=('variant', 'attribute'), name='unique_variant_attribute'),
        ),
    ]
