# Generated by Django 6.0.4 on 2026-04-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
