# Generated by Django 6.1 on 2026-08-23 06:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE catalog_product
                        ALTER COLUMN search_vector TYPE tsvector
                        USING to_tsvector(
                            'russian',
                            COALESCE(name, '') || ' ' || COALESCE(description, '')
                        );
                    """,
                    reverse_sql="""
                        ALTER TABLE catalog_product
                        ALTER COLUMN search_vector TYPE text
                        USING search_vector::text;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='product',
                    name='search_vector',
                    field=django.contrib.postgres.search.SearchVectorField(
                        blank=True,
                        editable=False,
                        help_text='Автоматически обновляется через trigger / celery. Не редактировать вручную.',
                        null=True,
                        verbose_name='Поисковый вектор',
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                condition=models.Q(status='active'),
                fields=['status', 'primary_category'],
                name='product_active_category_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                condition=models.Q(status='active'),
                fields=['status', 'brand'],
                name='product_active_brand_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                condition=models.Q(status='active'),
                fields=['-rating'],
                name='product_top_rating_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                condition=models.Q(status='active'),
                fields=['min_price'],
                name='product_price_asc_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                condition=models.Q(status='active'),
                fields=['-max_price'],
                name='product_price_desc_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                condition=models.Q(status='active'),
                fields=['-created_at'],
                name='product_newest_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(
                condition=models.Q(is_featured=True, status='active'),
                fields=['-created_at'],
                name='product_featured_partial_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['search_vector'],
                name='product_search_gin',
            ),
        ),
    ]
