# Generated by Django 6.0.4 on 2026-04-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_slug_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, null=True, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
    ]
