# Generated by Django 6.0.4 on 2026-05-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'Значение атрибут', 'verbose_name_plural': 'Значения атрибутов'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фото продукта', 'verbose_name_plural': 'Фото продуктов'},
        ),
        migrations.AlterModelOptions(
            name='variantattribute',
            options={'verbose_name': 'Вариант атрибута', 'verbose_name_plural': 'Варианты атрибутов'},
        ),
    ]
