# Generated by Django 6.1 on 2026-08-22 23:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('vote', models.CharField(choices=[('yes', 'Полезно'), ('no', 'Неполезно')], max_length=3, verbose_name='Голос')),
            ],
            options={
                'verbose_name': 'Голос за отзыв',
                'verbose_name_plural': 'Голоса за отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='reviews/%Y/%m/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Alt-текст')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фото к отзыву',
                'verbose_name_plural': 'Фото к отзывам',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('rating', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст отзыва')),
                ('verified_purchase', models.BooleanField(db_index=True, default=False, verbose_name='Подтверждённая покупка')),
                ('is_approved', models.BooleanField(db_index=True, default=True, help_text='False = скрыт до модерации.', verbose_name='Одобрен')),
                ('helpful_yes', models.PositiveIntegerField(default=0, verbose_name='Полезно')),
                ('helpful_no', models.PositiveIntegerField(default=0, verbose_name='Неполезно')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-created_at',),
            },
        ),
    ]
