# Generated by Django 6.0.6 on 2026-06-12 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('notification_type', models.CharField(choices=[('order_created', 'Заказ создан'), ('order_confirmed', 'Заказ подтверждён'), ('order_shipped', 'Заказ отправлен'), ('order_delivered', 'Заказ доставлен'), ('order_cancelled', 'Заказ отменён'), ('payment_success', 'Оплата прошла'), ('payment_failed', 'Ошибка оплаты'), ('shipment_in_transit', 'Посылка в пути'), ('shipment_delivered', 'Посылка доставлена'), ('review_reply', 'Ответ на отзыв'), ('promo', 'Промо-уведомление'), ('system', 'Системное')], db_index=True, max_length=30, verbose_name='Тип')),
                ('channel', models.CharField(choices=[('in_app', 'В приложении'), ('email', 'Email'), ('push', 'Push')], db_index=True, default='in_app', max_length=10, verbose_name='Канал')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, default='', max_length=2000, verbose_name='Текст')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('read', 'Прочитано')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('related_object_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Тип связанного объекта')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('action_url', models.URLField(blank=True, default='', verbose_name='URL действия')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='notif_user_status_idx'), models.Index(fields=['user', 'read_at'], name='notif_user_read_idx')],
            },
        ),
    ]
